### PR TITLE
Add instructions on how to compile software directly on FLPs

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy @bazinski this is what we need to compile on the FLP.

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
I will test it next week if possible

**Comment by bazinski** [comment]
@ktf shot will test it a bit later today.

**Comment by ktf** [comment]
Ok, can we merge this in the meanwhile?

**Comment by bazinski** [comment]
There is no alisw-MPFR+v3.1.3-67 in the configured yum repos in flp-169 the only mpfr is 
sudo yum list | grep -i mpfr
mpfr.x86_64                                3.1.1-4.el7            @base         
mpfr.i686                                  3.1.1-4.el7            base          
mpfr-devel.i686                            3.1.1-4.el7            base          
mpfr-devel.x86_64                          3.1.1-4.el7            base   

in the s3 hosted repo I can only find MPFR for osx.

**Comment by ktf** [comment]
Ok, I will check. It should not matter, in any case as that's only needed for fastjet.

**Comment by ktf** [comment]
Merging this since it's not completely crazy now.

**Comment by bazinski** [comment]
I had to change line 69 to 
` cmake ..  -DBUILD_TEST_ROOT_MACROS=OFF `

 then all working happily on flp169

**Pull request merged**
